# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170320_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.CharField(default='N/A', max_length=400),
        ),
    ]
