-- MySQL Script generated by MySQL Workbench
-- Mon Mar 13 00:27:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dojos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dojos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dojos` DEFAULT CHARACTER SET utf8 ;
USE `dojos` ;

-- -----------------------------------------------------
-- Table `dojos`.`dojos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dojos`.`dojos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dojos`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dojos`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `address1` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `dojo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_students_dojos1_idx` (`dojo_id` ASC),
  CONSTRAINT `fk_students_dojos1`
    FOREIGN KEY (`dojo_id`)
    REFERENCES `dojos`.`dojos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dojos`.`interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dojos`.`interests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dojos`.`student_interests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dojos`.`student_interests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `interest_id` INT NOT NULL,
  `student_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  INDEX `fk_interests_has_students_students1_idx` (`student_id` ASC),
  INDEX `fk_interests_has_students_interests_idx` (`interest_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_interests_has_students_interests`
    FOREIGN KEY (`interest_id`)
    REFERENCES `dojos`.`interests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interests_has_students_students1`
    FOREIGN KEY (`student_id`)
    REFERENCES `dojos`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
