# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170320_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(related_name='liked_secrets', to='main.User'),
        ),
    ]
