# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_secret_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='main.User'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='likes',
            field=models.ManyToManyField(to='main.User'),
        ),
    ]
